### ISSUE TITLE
Failing pandas compilation

### ISSUE THREAD

**Issue by philippjbauer** [unixwzrd/oobabooga-macOS#3]
Hi @unixwzrd,

thank you for putting this install guide together for us! 

I've followed the quickstart and everything worked so far but it breaks down compiling pandas with:
`pip install --no-cache --no-binary :all: --compile pandas`

I get the following error message:

```sh
➜ FORCE_CMAKE=1 pip install --no-cache --no-binary :all: --compile pandas
Collecting pandas
  Downloading pandas-2.0.3.tar.gz (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 13.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/__init__.py", line 153, in <module>
          from . import lib
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/lib/__init__.py", line 25, in <module>
          from .index_tricks import *
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
          import numpy.matrixlib as matrixlib
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
          from .defmatrix import *
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py", line 11, in <module>
          from numpy.linalg import matrix_power
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/linalg/__init__.py", line 73, in <module>
          from . import linalg
        File "/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 33, in <module>
          from numpy.linalg import lapack_lite, _umath_linalg
      ImportError: dlopen(/private/var/folders/d4/xd3y159j1d5dcz3kdg1xqz6m0000gn/T/pip-build-env-tchjtebn/overlay/lib/python3.10/site-packages/numpy/linalg/lapack_lite.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__gfortran_concat_string'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I searched for a resolution to this and found a suggestion to add `ADD_LDFLAGS="-lgfortran"` to the command but it didn't help, even in different variations (like e.g. `LDFLAGS="..."`).

Any idea how this could be fixed?

TIA

---

System: macOS 13.4.1 (c) on Apple M1 Pro

**Comment by philippjbauer** [comment]
I installed the regular `pandas` install from pip and tried running oobabooga (your version). Unfortunately I get the same error, apparently from the self-compiled `numpy` installation.

```sh
text-generation-webui on  main via 🅒 oobabooga took 4s
➜ python server.py
Traceback (most recent call last):
  File "/Users/philippbauer/Learning/MachineLearning/oobabooga/text-generation-webui/server.py", line 12, in <module>
    import gradio as gr
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 7, in <module>
    import numpy as np
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/__init__.py", line 144, in <module>
    from . import lib
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/lib/__init__.py", line 25, in <module>
    from . import index_tricks
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from . import defmatrix
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py", line 12, in <module>
    from numpy.linalg import matrix_power
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from . import linalg
  File "/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 35, in <module>
    from numpy.linalg import _umath_linalg
ImportError: dlopen(/Users/philippbauer/.miniforge3/envs/oobabooga/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__gfortran_concat_string'
(oobabooga)
```

I'll try the alternative conda installation described in the quickstart and let you know if that changes anything.

**Comment by unixwzrd** [comment]
I'll have a look at this now and see if I can replicate, I will be building a script which will handle the builds, working as fast as I can, there are some performance issues somewhere with llama-cpp-python  end exclamation for both mine and the original.  The code is pretty much common and hasn't diverged, is I'm looking into that.  I was thinking about rebuilding all my libraries again in a new venv.  If I do that, then I will be able to see if I can replicate the issue. 

You're  probably not going to have gFORTRAN on macOS or its libraries unless you get it from Brew.  I tried to avoid that. Next thing you know you have four or five package managers you have to worry about.  Pip and Conda i had to give in and accept them.

I'm on macOS 13.5, if you can manage not to do this update until they get it stable, I'd recommend it too.  WebKit crashes regularly and the Private Relay ends up breaking things like accessing OpenAI.  But hey, Time Machine is working again.

I'll let you know in a bit.

**Comment by philippjbauer** [comment]
I was able to get things running by installing numpy, pandas and the torch* packages through conda. Not sure if these they are using GPU acceleration though, that's not obvious to me.

> I'll have a look at this now and see if I can replicate, I will be building a script which will handle the builds, working as fast as I can, there are some performance issues somewhere with llama-cpp-python end exclamation for both mine and the original. The code is pretty much common and hasn't diverged, is I'm looking into that. I was thinking about rebuilding all my libraries again in a new venv. If I do that, then I will be able to see if I can replicate the issue.

Sounds like a plan, a script will be a great addition to this repo!

> You're probably not going to have gFORTRAN on macOS or its libraries unless you get it from Brew. I tried to avoid that. Next thing you know you have four or five package managers you have to worry about. Pip and Conda i had to give in and accept them.

Indeed I do not have gFORTRAN installed on my machine. I do have brew of course, might try it that way. I kind of accepted the fate of having all the package managers 😅 ... 

> I'm on macOS 13.5, if you can manage not to do this update until they get it stable, I'd recommend it too. WebKit crashes regularly and the Private Relay ends up breaking things like accessing OpenAI. But hey, Time Machine is working again.

Solid advice! I was actually planning to close everything out and install the update today (it's Sunday after all) ...

> I'll let you know in a bit.

Thank you!

**Comment by unixwzrd** [comment]
Ok, I think I have it figured out, drove me a bit nuts and this may also be why my environment is out of sync.  I usually use iTerm2, but for some testing purposes I forgot to uncheck the box on the "Get Info" pop-up for it.  But before i checked that, I went to VSCode and I know I have an ARM64 version of that installed for just tis very reason.  When things run in Rosetta, it makes everything think it's on Intel architecture, the only way you can tell if you're running under Rosetta is to:

'''bash
sysctl -n kern.versionI
'''

arch, and name will all tell you Intel, or better or worse i386.  This causes *LOTS* if inconsistencies.

'''bash
(base) [unixwzrd@xanax mps]$ uname -a
Darwin xanax.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 x86_64
(base) [unixwzrd@xanax mps]$ uname -m
x86_64
(base) [unixwzrd@xanax mps]$ arch
i386
'''

When I unchecked the box and went back in, pip worked perfectly. I even ran a diff on my environment variables and set them one by one, until Rosetta occurred to me.  Which also sadly, means that I probably have to restart my base build again because make is likely hosed due to incorrect reporting of uname and arch.

But if you could have a look at the terminal program you use, I would bet this is the issue, and you should probably change it so it's running native or you may experience unexpected issues like this.

But do run uname -m and arch also just to confirm you don't have an old Intel binary which migrated over from another machine somewhere. Let me know how this turns out.

Cheers!

**Comment by philippjbauer** [comment]
I RAN everything in iTerm.

Nothing indicates that it runs on Intel (see below), trying to install `gfortran` via brew just indicates that `gcc` is already installed. I did not migrate from my old Intel Mac when I set my new Apple Silicon machine up, so no old binaries from that either. \*scratches head\*

Here's my output ...

```bash
(oobabooga)
text-generation-webui on  main via 🅒 oobabooga
➜ brew install gfortran
Warning: gcc 13.1.0 is already installed and up-to-date.
To reinstall 13.1.0, run:
  brew reinstall gcc
(oobabooga)
text-generation-webui on  main via 🅒 oobabooga
➜ sysctl -n kern.version
Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
(oobabooga)
text-generation-webui on  main via 🅒 oobabooga
➜ uname -a
Darwin (redacted) 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
(oobabooga)
text-generation-webui on  main via 🅒 oobabooga
➜ uname -m
arm64
(oobabooga)
text-generation-webui on  main via 🅒 oobabooga
➜ arch
arm64
```

Now I'm confused why I get the issues with `gfortran` ... doesn't make much sense if it's part of `gcc`?!

**Comment by unixwzrd** [comment]
Yes, basically for every language in the GNU ecosystem, they essentially translate the code into C, then use the C compiler to create the assembly code and that then gets assembled and linked into an executable.  So, C++, Objective-C, FORTRAN, Ada, and more are just translating to C. There may be a bit more than that, but that's essentially what happens.

You could do a:

which gcc
gcc --version

That will tell you where it's installed and what version, the apple compiler will report this:

(base) [unixwzrd@xanax mps]$ gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Changing the name of the folder will work.  I may change the name of both my repositories before they get too big.  The scripts I am working on to build/rebuild Python packages and start oobagooba are entirely shell scripts and will take only a few variables to adjust and you'll be able to run it from anywhere pretty much.  Hopefully, after I get the environment rebuilt on my machine, I'll commit a dev build which will be similar to the original-gooba version 1.5.

If you could get me the output of this command, I might be able to see something:

env | sort > emvlist.txt

I believe you can send me a private message through GitHub if you don't want your environment open to public view.

Be well...

**Comment by unixwzrd** [comment]
Also, if you could send me the output of your pip command:

pip install --no-cache --no-binary :all: package pandas --compile -v  2>&1  > pipout.txt

That would be helpful too. Replace pandas with which ever package you are having a problem with.

**Comment by unixwzrd** [comment]
Just a quick update for you.  I hadn't got a chance to circle back to this, but in rebuilding my environment, I notice that your error output also has a reference to LAPACK, that's the Linear Algebra PACK for optimizing linear algebra calculations.  I also notice from the traceback that it's complaining at the numpy module.  NumPy is the package which requires BLAS and LAPACK, so this is the issue. BLAS and LAPACK parts were also written in FORTRN, but you can get around that with several BLAS versions available, like OpenBLAS. I winder if you managed to get OpenBLAS installed as I described in the instructions for NumPy

There is a possibly better solution, though I am still investigating for an even faster BLAS/LAPACK implementation, is Apple's Accelerate Framework, which is specifically for matrix manipulation of all varieties. There isn't much in the way of documentation on this, but I did find some references to it in the NumPy 1.20.0 release notes regarding the use of the Accelerate Framework.

To compile NumPy with Accelerate do this:

NPY_BLAS_ORDER='accelerate' \
    NPY_LAPACK_ORDER='accelerate' \
    pip install --no-cache --no-binary :all: --compile numpy

This will make the build look for the accelerate framework, which runs benchmarks quite faster.  I built NumPy in two different venv's and using accelerate was about twice as fast, but I did not run a full set of benchmarks on it. I did write a quick Pyrton script to use in gathering performance numbers which will give an overall impression of performance. It also displays the NumPy configuration and what BLAS and LAPACK libraries were linked into it.

My Pandas build using the pip command went without a problem for me. My only thought i that it may have been something in your NumPy build where it did not find the BLAS/LAPACK libraries.

Hope that helps.

**Comment by philippjbauer** [comment]
I have tried the whole process again but replaced the numpy compilation step with this one. Unfortunately it still breaks in the same way it did before.

Afterwards I have installed the `pytorch-nightly` as described here https://developer.apple.com/metal/pytorch ... this installation includes `numpy` but I'm not sure if it is an optimized packet. Inference with OpenOrcaxOpenChat-Preview2-13B GGML q4km model is pretty fast. I just started a chat and asked a bunch of questions with the following speeds. Is this about comparable with what you get?

```
Output generated in 16.05 seconds (4.42 tokens/s, 71 tokens, context 72, seed 490989326)
Llama.generate: prefix-match hit
Output generated in 7.74 seconds (9.04 tokens/s, 70 tokens, context 149, seed 887675114)
Llama.generate: prefix-match hit
Output generated in 8.00 seconds (9.00 tokens/s, 72 tokens, context 225, seed 1980407119)
Llama.generate: prefix-match hit
Output generated in 7.34 seconds (8.32 tokens/s, 61 tokens, context 307, seed 2028186750)
Llama.generate: prefix-match hit
Output generated in 8.56 seconds (7.94 tokens/s, 68 tokens, context 383, seed 1703941881)
Llama.generate: prefix-match hit
Output generated in 9.59 seconds (8.44 tokens/s, 81 tokens, context 459, seed 2011651036)
Llama.generate: prefix-match hit
Output generated in 8.61 seconds (8.37 tokens/s, 72 tokens, context 546, seed 1147625956)
Llama.generate: prefix-match hit
Output generated in 8.87 seconds (8.01 tokens/s, 71 tokens, context 627, seed 1473276193)
Llama.generate: prefix-match hit
Output generated in 12.96 seconds (8.03 tokens/s, 104 tokens, context 709, seed 965449207)
Llama.generate: prefix-match hit
Output generated in 34.45 seconds (7.89 tokens/s, 272 tokens, context 840, seed 682873289)
Llama.generate: prefix-match hit
Output generated in 37.27 seconds (7.94 tokens/s, 296 tokens, context 1124, seed 1768672639)
Llama.generate: prefix-match hit
Output generated in 12.24 seconds (7.02 tokens/s, 86 tokens, context 1433, seed 1617041224)
Llama.generate: prefix-match hit
Output generated in 146.51 seconds (3.25 tokens/s, 476 tokens, context 1533, seed 561485054)
```

**Comment by unixwzrd** [comment]
Ok, I'll do this right now.  I am building a new fresh VENV before  testing some other configuration issues.  I will list out each step here in my  guild start to finish. I'll start in about 10 minutes from now at 30 minutes past the hour. Updates will be attached here.

**Comment by unixwzrd** [comment]
That's really good speed, I'm usually running 30B q4 bit models and can get anywhere between 1.5 to about 7.5 tps, so your eyeballing as an average of about 7tps is pretty good.

How big is your context (n_ctx) and how big are your prompts and responses, it looks pretty good overall.  I do find the the GGML tends to get slower with time, are you observing that?  And by slower, I am speaking of using llama.cpp standalone and as llama-cpp-python. I also seem to observe more CPU oriented processing with the libggml/libllama processing.

Still not sure why your numpy is failing, I haven't had any problems with it so far. Sometimes long prompts run quickly for me, and sometimes a short prompt takes a long time.

**Comment by unixwzrd** [comment]
The libraries and packages are all a moving target. PyTorch, just this past week , needs to be installed from the weekly builds using Pip from their USL. But installing everything from the package repositories using Conda works, and if it works for you, then great.  I find that NumPy seems to be the key package which needs the accretion.
But if your bpackage builds work for you, keep using them.  I'm closing out this ticket since you have it solved.
