### ISSUE TITLE
bitsandbytes issue still there

### ISSUE THREAD

**Issue by jhandl** [unixwzrd/oobabooga-macOS#4]
I just followed all the instructions in the "impatient" script, opting for the text-generation-webui-macos trunk version (not test or dev), and when running the start-webui script I get:

```
(webui.04.final-gguf) jhandl@macmini webui-macOS % ./start.sh 
/Users/jhandl/miniconda3/envs/webui.04.final-gguf/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of **bitsandbytes was compiled without GPU support**. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "/Users/jhandl/webui-macOS/server.py", line 6, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "/Users/jhandl/webui-macOS/modules/chat.py", line 17, in <module>
    from modules.text_generation import (
  File "/Users/jhandl/webui-macOS/modules/text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache
  File "/Users/jhandl/webui-macOS/modules/models.py", line 23, in <module>
    from modules.models_settings import infer_loader
  File "/Users/jhandl/webui-macOS/modules/models_settings.py", line 31
    elif re.match('.*gguf.*\.bin', model_name.lower()):
                                                       ^
**IndentationError: unindent does not match any outer indentation level**
```

After fixing the indentation issue the server started, but no matter what I tried, all I got was the input instantly copied to the output and nothing else, with the server reporting that it generated 0 tokens, at a pace of 0.00 tokens/s, in 0.23 seconds.

I then cloned the original Oobabooga repo (following the "impatient" instructions), and now Oobabooga worked, but at 0.06 tokens/s, so not using the GPU. I also monitored the GPU usage through the Activity Monitor and it was clearly at 0 the whole time.

Setup: Mac mini M2 Pro 16 GB, Mac OS 13.5.2

**Comment by unixwzrd** [comment]
Hi, thanks for reporting this issue, I appreciate the testing. I am working n this and moving it over to the correct repository.

https://github.com/unixwzrd/text-generation-webui-macos/issues/12#issue-1899685738

I'm looking into this now. Please follow-up there.

Thanks!
